kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - secrets
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - services
  - secrets
  verbs:
  - update
- apiGroups:
  - "route.openshift.io"
  resources:
  - routes
  verbs:
  - "*"
- apiGroups:
  - "route.openshift.io"
  resources:
  - routes/custom-host
  verbs:
  - "update"
- apiGroups:
  - extensions
  resources:
  - replicasets
  - deployments
  verbs:
  - "get"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
- apiGroups:
  - extensions
  resources:
  - deployments/finalizers
  resourceNames:
  - cert-operators
  verbs:
  - "update"