apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-operator-role
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - events
    - configmaps
    - secrets
    verbs:
    - "*"
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
    verbs:
    - "*"
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    verbs:
    - "get"
    - "create"
  - apiGroups:
    - apps
    resources:
    - deployments/finalizers
    resourceNames:
    - cert-operator
    verbs:
    - update
  - apiGroups:
    - ""
    resources:
    - services
    - routes
    - configmaps
    - services
    verbs:
    - create