apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-operator
roleRef:
  kind: ClusterRole
  name: cert-operator-role
subjects:
- kind: ServiceAccount
  name: cert-operator
